import { useState } from "react";
import { BookOpen, ChevronDown, ChevronUp, HelpCircle, MapPin } from "lucide-react";
import { T, font } from "../../lib/theme";
import { HELP_CONTACT } from "../../lib/helpContact";

const STEPS = [
  [1,"Login ke Si Lapak Priok","Masuk menggunakan akun Si Lapak Priok yang telah terdaftar."],
  [2,"Atur Petugas Jaga","Tetapkan petugas yang sedang bertugas sebelum mulai mencatat paket atau tamu."],
  [3,"Tambah Paket Masuk","Isi data pengirim, penerima, ekspedisi, dan foto paket jika tersedia."],
  [4,"Proses Pengambilan Paket","Cari paket pada Data Paket, lalu catat pengambil dan bukti pengambilan."],
  [5,"Catat Kunjungan Tamu","Gunakan Buku Tamu untuk mencatat identitas, tujuan, dan waktu kunjungan."],
  [6,"Lihat Riwayat","Gunakan Riwayat untuk menelusuri data paket dan tamu yang pernah dicatat."],
];
const FAQ=[
  ["Bagaimana mengubah data paket yang sudah tersimpan?","Buka Data Paket, pilih data yang diperlukan, lalu gunakan aksi edit yang tersedia."],
  ["Bagaimana jika paket sudah diambil tetapi belum diproses?","Gunakan Proses Ambil pada Data Paket dan lengkapi data pengambil serta bukti yang tersedia."],
  ["Apa yang dilakukan jika mengalami kendala?","Hubungi admin melalui WhatsApp pada bagian Kontak Admin di halaman ini."],
];
function WA({size=17,color="currentColor"}){return <svg width={size} height={size} viewBox="0 0 24 24" aria-hidden="true"><path fill={color} d="M20.5 3.5A11.8 11.8 0 0 0 12.1 0C5.6 0 .2 5.3.2 11.9c0 2.1.6 4.1 1.6 5.9L.1 24l6.4-1.7a11.8 11.8 0 0 0 5.6 1.4C18.7 23.8 24 18.4 24 11.9c0-3.2-1.2-6.2-3.5-8.4Zm-8.4 18.3a9.8 9.8 0 0 1-5-1.4l-.4-.2-3.8 1 1-3.7-.2-.4a9.9 9.9 0 1 1 8.4 4.7Zm5.4-7.4c-.3-.2-1.8-.9-2-.9-.3-.1-.5-.2-.7.1-.2.3-.8 1-.9 1.2-.2.2-.4.2-.7.1-.3-.2-1.2-.5-2.4-1.5-.9-.8-1.5-1.8-1.6-2-.2-.3 0-.5.1-.6.1-.2.3-.4.5-.6.1-.2.2-.3.3-.5.1-.2 0-.4 0-.5-.1-.2-.7-1.6-.9-2.2-.3-.6-.5-.5-.7-.5h-.6c-.2 0-.5.1-.8.4-.3.3-1 1-1 2.5s1.1 2.9 1.2 3.1c.2.2 2.1 3.2 5.1 4.5.7.3 1.3.5 1.7.6.7.2 1.4.2 1.9.1.6-.1 1.8-.7 2-1.4.3-.7.3-1.3.2-1.4-.1-.1-.3-.2-.6-.3Z"/></svg>}
function Faq({q,a}){const[open,setOpen]=useState(false);return <div style={{border:`1px solid ${T.border}`,borderRadius:10,overflow:"hidden",marginBottom:9}}><button onClick={()=>setOpen((p)=>!p)} style={{width:"100%",padding:"13px 15px",display:"flex",alignItems:"center",justifyContent:"space-between",gap:10,background:open?T.blueSoft:T.card,border:0,color:T.heading,textAlign:"left",fontWeight:700,cursor:"pointer"}}><span>{q}</span>{open?<ChevronUp size={15}/>:<ChevronDown size={15}/>}</button>{open&&<div style={{padding:"12px 15px",borderTop:`1px solid ${T.border}`,fontSize:12.5,color:T.muted,lineHeight:1.6}}>{a}</div>}</div>}
export default function SiLapakBantuan(){const wa=`https://wa.me/${HELP_CONTACT.waNumber}?text=${encodeURIComponent(HELP_CONTACT.waMessage)}`;return <div style={{maxWidth:820,minWidth:0}}><h2 style={{fontSize:18,fontWeight:800,color:T.heading,margin:"0 0 4px"}}>Bantuan Si Lapak Priok</h2><p style={{fontSize:12.5,color:T.muted,margin:"0 0 24px"}}>Panduan, FAQ, dan kontak bantuan.</p><section style={section}><Title icon={BookOpen} text="Panduan Penggunaan"/><div className="responsive-card-grid" style={{display:"grid",gridTemplateColumns:"repeat(2,minmax(0,1fr))",gap:10}}>{STEPS.map(([no,title,desc])=><div key={no} style={{padding:12,borderRadius:10,border:`1px solid ${T.border}`,background:T.bg}}><div style={{display:"flex",gap:8,alignItems:"center",marginBottom:6}}><span style={{width:24,height:24,borderRadius:"50%",display:"grid",placeItems:"center",background:"#FDEA6F",color:"#302800",fontWeight:800,fontSize:11}}>{no}</span><b style={{fontSize:12.5,color:T.heading}}>{title}</b></div><div style={{fontSize:11.5,color:T.muted,lineHeight:1.55}}>{desc}</div></div>)}</div></section><section style={section}><Title icon={HelpCircle} text="Pertanyaan Umum"/>{FAQ.map(([q,a])=><Faq key={q} q={q} a={a}/>)}</section><section style={section}><div style={{fontSize:14,fontWeight:800,color:T.heading,marginBottom:5}}>Kontak Admin</div><div style={{fontSize:12,color:T.muted,marginBottom:14}}>Jam operasional: {HELP_CONTACT.hours}</div><div className="responsive-card-grid" style={{display:"grid",gridTemplateColumns:"repeat(2,minmax(0,1fr))",gap:10}}><a href={wa} target="_blank" rel="noopener noreferrer" style={{...contact,textDecoration:"none"}}><span style={{width:34,height:34,borderRadius:"50%",background:"#25D366",display:"grid",placeItems:"center",color:"#fff"}}><WA color="#fff"/></span><div><div style={{fontSize:11,color:T.muted}}>WhatsApp</div><div style={{fontSize:13,fontWeight:800,color:T.heading}}>{HELP_CONTACT.phone}</div></div></a><div style={contact}><span style={{width:34,height:34,borderRadius:8,background:T.blueSoft,display:"grid",placeItems:"center",color:T.blue}}><MapPin size={16}/></span><div><div style={{fontSize:11,color:T.muted}}>Lokasi</div><div style={{fontSize:12.5,fontWeight:700,color:T.heading}}>UBP Priok, Jakarta Utara</div></div></div></div></section></div>}
function Title({icon:Icon,text}){return <div style={{display:"flex",alignItems:"center",gap:8,marginBottom:14}}><div style={{width:32,height:32,borderRadius:9,background:"#FFF9D5",display:"grid",placeItems:"center",color:"#8C7600"}}><Icon size={16}/></div><b style={{fontSize:14,color:T.heading}}>{text}</b></div>}
const section={background:T.card,border:`1px solid ${T.border}`,borderRadius:14,padding:"18px 20px",marginBottom:18};const contact={display:"flex",alignItems:"center",gap:10,padding:"12px 13px",borderRadius:10,border:`1px solid ${T.border}`,background:T.bg,minWidth:0};
