import { useMemo, useState } from "react";
import { Eye, Plus, Printer, Search, Trash2, Upload, Users } from "lucide-react";
import { T, font } from "../../lib/theme";
import { uid } from "../../lib/utils";
import PageHeader from "../../components/PageHeader";
import Card from "../../components/Card";
import Modal from "../../components/Modal";
import UploadDocModal from "../../components/UploadDocModal";

const rabNo=(id="")=>Number(String(id).match(/(\d+)(?!.*\d)/)?.[1]||-1);
export default function DaftarHadirPage({rab,notify}){
  const [lists,setLists]=useState([]),[docs,setDocs]=useState([]),[query,setQuery]=useState(""),[showForm,setShowForm]=useState(null),[showUpload,setShowUpload]=useState(null),[preview,setPreview]=useState(null),[name,setName]=useState(""),[instansi,setInstansi]=useState("");
  const sorted=useMemo(()=>[...(rab||[])].sort((a,b)=>rabNo(b.idNumber)-rabNo(a.idNumber)||String(b.idNumber).localeCompare(String(a.idNumber),"id",{numeric:true})),[rab]);
  const filtered=useMemo(()=>{const q=query.trim().toLowerCase();return q?sorted.filter((r)=>String(r.idNumber).toLowerCase().includes(q)||String(r.judulKegiatan||"").toLowerCase().includes(q)):sorted},[query,sorted]);
  const has=(r)=>lists.some((x)=>x.rabId===r.idNumber)||docs.some((x)=>x.rabId===r.idNumber);
  const done=filtered.filter(has),pending=filtered.filter((r)=>!has(r));
  const add=(rabId)=>{if(!name.trim())return;setLists((p)=>[...p,{id:uid("DH"),rabId,nama:name.trim(),instansi:instansi.trim(),waktu:new Date().toISOString()}]);setName("");setInstansi("");notify?.("Peserta ditambahkan.","success")};
  const upload=(r,files)=>{if(!r)return;setDocs((p)=>[...p,...files.map((f)=>({id:uid("DH-DOC"),rabId:r.idNumber,fileName:f.name,fileSize:f.size,fileType:f.type,url:URL.createObjectURL(f)}))]);notify?.("File daftar hadir berhasil disimpan.","success","Upload Daftar Hadir")};
  const print=(r)=>{const rows=lists.filter((x)=>x.rabId===r.idNumber).map((x,i)=>`${i+1}. ${x.nama} | ${x.instansi||"-"}`).join("\n");const w=window.open("","_blank");if(!w)return;w.document.write(`<pre style="font:14px Arial;white-space:pre-wrap;padding:32px"><b>DAFTAR HADIR</b>\n${r.idNumber}\n${r.judulKegiatan}\n\n${rows||"Belum ada peserta"}</pre>`);w.document.close();setTimeout(()=>w.print(),150)};
  return <div><PageHeader eyebrow="Pelaksanaan" title="Daftar Hadir" description="Cari ID RAB dan pantau RAB yang sudah maupun belum memiliki daftar hadir."/><div className="responsive-toolbar" style={toolbar}><div style={{position:"relative",flex:"1 1 360px"}}><Search size={15} color={T.muted} style={searchIcon}/><input value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="Cari ID RAB atau judul kegiatan..." style={searchInput}/></div><span style={{fontSize:12,color:T.muted}}>{filtered.length} RAB</span></div>{!rab?.length?<Card><Empty text="Belum ada RAB."/></Card>:<div className="responsive-two-col" style={{display:"grid",gridTemplateColumns:"repeat(2,minmax(0,1fr))",gap:16,alignItems:"start"}}><Column title="Sudah Ada Daftar Hadir" count={done.length} ok>{done.length?done.map((r)=><RabCard key={r.idNumber} r={r} entries={lists.filter((x)=>x.rabId===r.idNumber)} files={docs.filter((x)=>x.rabId===r.idNumber)} open={showForm===r.idNumber} onToggle={()=>setShowForm(showForm===r.idNumber?null:r.idNumber)} name={name} setName={setName} instansi={instansi} setInstansi={setInstansi} onAdd={()=>add(r.idNumber)} onUpload={()=>setShowUpload(r)} onPrint={()=>print(r)} onDeleteEntry={(id)=>setLists((p)=>p.filter((x)=>x.id!==id))} onDeleteFile={(id)=>setDocs((p)=>p.filter((x)=>x.id!==id))} onPreview={setPreview}/>):<Empty text="Belum ada daftar hadir."/>}</Column><Column title="Belum Ada Daftar Hadir" count={pending.length}>{pending.length?pending.map((r)=><RabCard key={r.idNumber} r={r} entries={[]} files={[]} open={showForm===r.idNumber} onToggle={()=>setShowForm(showForm===r.idNumber?null:r.idNumber)} name={name} setName={setName} instansi={instansi} setInstansi={setInstansi} onAdd={()=>add(r.idNumber)} onUpload={()=>setShowUpload(r)} onPrint={()=>print(r)} onDeleteEntry={()=>{}} onDeleteFile={()=>{}} onPreview={setPreview}/>):<Empty text="Semua RAB sudah memiliki daftar hadir."/>}</Column></div>}<UploadDocModal open={!!showUpload} onClose={()=>setShowUpload(null)} title={showUpload?`Upload Daftar Hadir - ${showUpload.idNumber}`:""} subtitle={showUpload?.judulKegiatan} accept="image/*,.pdf,.doc,.docx" onSave={(files)=>upload(showUpload,files)}/>{preview&&<Modal open onClose={()=>setPreview(null)} title={preview.fileName} icon={Eye} width={600}>{preview.fileType?.startsWith("image/")?<img src={preview.url} alt={preview.fileName} style={{width:"100%",maxHeight:"70vh",objectFit:"contain",borderRadius:8}}/>:<div style={{padding:28,textAlign:"center"}}><a href={preview.url} download={preview.fileName} style={{color:T.blue,fontWeight:700}}>Download file</a></div>}</Modal>}</div>
}
function Column({title,count,ok,children}){return <section style={{minWidth:0}}><div style={{display:"flex",justifyContent:"space-between",gap:10,alignItems:"center",marginBottom:10}}><b style={{fontFamily:font.display,fontSize:14,color:T.heading}}>{title}</b><span style={{padding:"4px 9px",borderRadius:999,background:ok?T.successSoft:"#FFF4D0",color:ok?T.success:"#8A6D00",fontSize:11.5,fontWeight:800}}>{count}</span></div><div style={{display:"grid",gap:10}}>{children}</div></section>}
function RabCard({r,entries,files,open,onToggle,name,setName,instansi,setInstansi,onAdd,onUpload,onPrint,onDeleteEntry,onDeleteFile,onPreview}){return <Card><div style={{fontFamily:font.mono,fontSize:12,fontWeight:800,color:T.blue}}>{r.idNumber}</div><div style={{fontSize:13.5,fontWeight:700,color:T.heading,lineHeight:1.45,marginTop:3,overflowWrap:"anywhere"}}>{r.judulKegiatan}</div><div className="responsive-actions attendance-actions" style={{display:"grid",gridTemplateColumns:"repeat(3,minmax(0,1fr))",gap:8,marginTop:12}}><button onClick={onToggle} style={btn}><Plus size={14}/>Tambah</button><button onClick={onUpload} style={btn}><Upload size={14}/>Upload</button><button onClick={onPrint} style={btn}><Printer size={14}/>Cetak</button></div>{open&&<div className="responsive-form-grid" style={{display:"grid",gridTemplateColumns:"repeat(2,minmax(0,1fr))",gap:8,marginTop:10}}><input value={name} onChange={(e)=>setName(e.target.value)} placeholder="Nama peserta" style={input}/><input value={instansi} onChange={(e)=>setInstansi(e.target.value)} placeholder="Instansi" style={input}/><button onClick={onAdd} style={{...btn,gridColumn:"1 / -1",background:T.blue,color:"#fff",borderColor:T.blue}}>Simpan Peserta</button></div>}{entries.length>0&&<div style={{marginTop:12,display:"grid",gap:6}}>{entries.map((x,i)=><div key={x.id} style={row}><span style={{fontSize:11,color:T.muted,width:20}}>{i+1}</span><div style={{flex:1,minWidth:0}}><div style={{fontSize:12.5,fontWeight:700,color:T.heading}}>{x.nama}</div><div style={{fontSize:10.5,color:T.muted}}>{x.instansi||"-"}</div></div><button onClick={()=>onDeleteEntry(x.id)} style={icon}><Trash2 size={13}/></button></div>)}</div>}{files.length>0&&<div style={{marginTop:10,display:"grid",gap:6}}>{files.map((x)=><div key={x.id} style={row}>{x.fileType?.startsWith("image/")?<img src={x.url} alt="" style={{width:30,height:30,borderRadius:5,objectFit:"cover"}}/>:<Users size={15} color={T.muted}/>}<span style={{flex:1,minWidth:0,overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap",fontSize:11.5,fontWeight:700}}>{x.fileName}</span><button onClick={()=>onPreview(x)} style={icon}><Eye size={13}/></button><button onClick={()=>onDeleteFile(x.id)} style={icon}><Trash2 size={13}/></button></div>)}</div>}<div style={{fontSize:10.5,color:T.muted,marginTop:10}}>Peserta {entries.length} · File {files.length}</div></Card>}
function Empty({text}){return <div style={{padding:"20px 12px",textAlign:"center",color:T.muted,fontSize:12.5}}>{text}</div>}
const toolbar={display:"flex",alignItems:"center",gap:10,marginBottom:18};const searchIcon={position:"absolute",left:12,top:"50%",transform:"translateY(-50%)"};const searchInput={width:"100%",height:42,padding:"0 12px 0 38px",borderRadius:9,border:"1px solid var(--border)",background:"var(--input-bg)",color:"var(--text)"};const btn={display:"inline-flex",alignItems:"center",justifyContent:"center",gap:6,minHeight:36,padding:"0 10px",borderRadius:8,border:"1px solid var(--border)",background:"var(--card)",color:"var(--blue)",cursor:"pointer",fontSize:11.5,fontWeight:700};const input={width:"100%",padding:"9px 10px",borderRadius:8,border:"1px solid var(--border)",background:"var(--input-bg)",color:"var(--text)"};const row={display:"flex",alignItems:"center",gap:8,padding:"8px 9px",borderRadius:8,border:"1px solid var(--border)",background:"var(--bg)",minWidth:0};const icon={width:27,height:27,display:"grid",placeItems:"center",border:0,background:"transparent",color:T.danger,cursor:"pointer",flexShrink:0};
