import { useEffect, useState } from "react";
import { ArrowRight, CheckCircle2, Clock, FileText, Send, XCircle } from "lucide-react";
import { T, font } from "../../lib/theme";
import { MITRA_STATUS_META } from "../../lib/data";
import { rupiah } from "../../lib/utils";

function LiveClock(){const[now,setNow]=useState(new Date());useEffect(()=>{const t=setInterval(()=>setNow(new Date()),1000);return()=>clearInterval(t)},[]);return <div><div style={{fontSize:12.5,color:"rgba(255,255,255,.72)",marginBottom:2}}>{now.toLocaleDateString("id-ID",{weekday:"long",day:"numeric",month:"long",year:"numeric"})}</div><div style={{fontSize:"clamp(21px,4vw,28px)",fontWeight:800,color:"#fff"}}>{now.toLocaleTimeString("id-ID",{hour:"2-digit",minute:"2-digit",second:"2-digit"})} <span style={{fontSize:12,fontWeight:600,opacity:.65}}>WIB</span></div></div>}
function greeting(){const h=new Date().getHours();return h<11?"Selamat Pagi":h<15?"Selamat Siang":h<18?"Selamat Sore":"Selamat Malam"}
function Stat({label,value,icon:Icon,color,bg}){return <div style={{background:T.card,border:`1px solid ${T.border}`,borderRadius:12,padding:"16px 18px",display:"flex",alignItems:"center",gap:12,minWidth:0}}><div style={{width:42,height:42,borderRadius:10,background:bg,display:"grid",placeItems:"center",flexShrink:0}}><Icon size={19} color={color}/></div><div><div style={{fontSize:22,fontWeight:800,color:T.heading}}>{value}</div><div style={{fontSize:12,color:T.muted,lineHeight:1.35}}>{label}</div></div></div>}
function Badge({status}){const meta=MITRA_STATUS_META[status]||{label:status,color:"#94A3B8",bg:"#F1F5F9"};return <span style={{display:"inline-flex",alignItems:"center",gap:5,padding:"4px 9px",borderRadius:999,background:meta.bg,color:meta.color,fontSize:11,fontWeight:800,whiteSpace:"nowrap"}}><span style={{width:5,height:5,borderRadius:"50%",background:meta.color}}/>{meta.label}</span>}
function Flow(){return <div style={{background:T.card,border:`1px solid ${T.border}`,borderRadius:12,padding:"16px 18px",marginBottom:22}}><div style={{fontSize:13,fontWeight:800,color:T.heading,marginBottom:12}}>Alur Pengajuan GANDENG</div><div style={{display:"flex",alignItems:"center",gap:8,overflowX:"auto",paddingBottom:2}}>{["Pengajuan","Humas","ASMAN","MADM","Selesai"].map((s,i)=><div key={s} style={{display:"flex",alignItems:"center",gap:8,flexShrink:0}}><div style={{display:"inline-flex",alignItems:"center",gap:6,padding:"7px 10px",borderRadius:8,background:i===0?T.blueSoft:T.bg,border:`1px solid ${T.border}`,color:i===0?T.blue:T.text,fontSize:11.5,fontWeight:800}}>{i===0&&<Send size={13}/>} {s}</div>{i<4&&<ArrowRight size={13} color={T.muted}/>}</div>)}</div></div>}

export default function GandengDashboard({mitraList,user,onGoto}){
  const total=mitraList.length,diproses=mitraList.filter((m)=>m.status?.startsWith("diproses")).length,disetujui=mitraList.filter((m)=>m.status==="disetujui").length,ditolak=mitraList.filter((m)=>m.status?.startsWith("ditolak")).length;
  const recent=[...mitraList].sort((a,b)=>new Date(b.createdAt||0)-new Date(a.createdAt||0)).slice(0,3);
  return <div style={{fontFamily:font.body,padding:"clamp(18px,3vw,28px) clamp(16px,4vw,32px)",maxWidth:1100,width:"100%",boxSizing:"border-box"}}>
    <div style={{background:"linear-gradient(135deg,#780000 0%,#CF0000 100%)",borderRadius:16,padding:"clamp(20px,4vw,28px) clamp(20px,4vw,32px)",marginBottom:22,display:"flex",justifyContent:"space-between",alignItems:"center",gap:20,flexWrap:"wrap",boxShadow:"0 8px 32px rgba(207,0,0,.18)"}}><div style={{minWidth:0,flex:"1 1 320px"}}><div style={{fontSize:13,color:"rgba(255,255,255,.7)",marginBottom:5}}>{greeting()}, <strong style={{color:"#fff"}}>{user?.organization||user?.name||"Pengguna"}</strong></div><div style={{fontSize:"clamp(19px,3vw,23px)",fontWeight:800,color:"#fff",marginBottom:5}}>Selamat datang di GANDENG</div><div style={{fontSize:13,color:"rgba(255,255,255,.72)",lineHeight:1.6,maxWidth:560}}>Ajukan proposal dan pantau proses pemeriksaan dari Humas, ASMAN, sampai MADM.</div></div><LiveClock/></div>
    <Flow/>
    <div className="responsive-card-grid" style={{display:"grid",gridTemplateColumns:"repeat(4,minmax(0,1fr))",gap:14,marginBottom:22}}><Stat label="Total Pengajuan" value={total} icon={FileText} color={T.blue} bg={T.blueSoft}/><Stat label="Sedang Diproses" value={diproses} icon={Clock} color="#8A6D00" bg="#FFF4D0"/><Stat label="Disetujui" value={disetujui} icon={CheckCircle2} color="#1E7F3E" bg="#DEF6E5"/><Stat label="Perlu Revisi / Ditolak" value={ditolak} icon={XCircle} color="#B01818" bg="#FCE1E1"/></div>
    <div style={{background:T.card,border:`1px solid ${T.border}`,borderRadius:12,overflow:"hidden"}}><div style={{padding:"16px 20px",borderBottom:`1px solid ${T.border}`,display:"flex",alignItems:"center",justifyContent:"space-between",gap:12,flexWrap:"wrap"}}><div style={{fontSize:14,fontWeight:800,color:T.heading}}>Pengajuan Terbaru</div><button onClick={()=>onGoto("riwayat")} style={linkBtn}>Lihat semua <ArrowRight size={13}/></button></div>{recent.length===0?<div style={{padding:"32px 20px",textAlign:"center",color:T.muted,fontSize:13,lineHeight:1.6}}>Belum ada pengajuan pada akun ini.</div>:recent.map((m,i)=><div key={m.id} style={{padding:"14px 20px",borderBottom:i<recent.length-1?`1px solid ${T.border}`:"none",display:"flex",alignItems:"center",justifyContent:"space-between",gap:12,flexWrap:"wrap"}}><div style={{minWidth:0,flex:"1 1 260px"}}><div style={{fontSize:13,fontWeight:700,color:T.heading,marginBottom:3,lineHeight:1.45,overflowWrap:"anywhere"}}>{m.judulPengajuan}</div><div style={{fontSize:11,color:T.muted,lineHeight:1.5}}>{m.namaLembaga} · {m.nilaiDiajukan?rupiah(m.nilaiDiajukan):"-"}</div></div><Badge status={m.status}/></div>)}</div>
    <div className="responsive-actions" style={{display:"flex",gap:12,marginTop:20}}><button onClick={()=>onGoto("pengajuan-baru")} style={primary}>+ Buat Pengajuan Baru</button><button onClick={()=>onGoto("tracking")} style={secondary}>Tracking Status</button></div>
  </div>
}
const linkBtn={display:"flex",alignItems:"center",gap:4,background:"none",border:0,color:T.blue,cursor:"pointer",fontSize:12,fontWeight:700};const primary={padding:"11px 20px",borderRadius:8,border:0,background:"var(--blue)",color:"#fff",cursor:"pointer",fontSize:13,fontWeight:800};const secondary={padding:"11px 20px",borderRadius:8,border:"1px solid var(--border)",background:"var(--card)",color:"var(--text)",cursor:"pointer",fontSize:13,fontWeight:700};
