import { useState } from "react";
import { CheckCircle2, ChevronRight, Eye, Plus, Send, XCircle } from "lucide-react";
import { T, font } from "../../lib/theme";
import { MITRA_STATUS, MITRA_STATUS_META } from "../../lib/data";
import { uid, rupiah } from "../../lib/utils";
import Card from "../../components/Card";
import PageHeader from "../../components/PageHeader";
import Modal from "../../components/Modal";

const STEPS=["Humas","ASMAN","MADM","Disetujui"];
const stepFromStatus=(status)=>MITRA_STATUS_META[status]?.step||0;
const isRejected=(status)=>status?.startsWith("ditolak");
function StatusBadge({status}){const meta=MITRA_STATUS_META[status]||{label:status,color:"#94A3B8",bg:"#F1F5F9"};return <span style={{display:"inline-flex",alignItems:"center",gap:5,padding:"4px 9px",borderRadius:999,background:meta.bg,color:meta.color,fontSize:11,fontWeight:800,whiteSpace:"nowrap"}}><span style={{width:6,height:6,borderRadius:"50%",background:meta.color}}/>{meta.label}</span>}
function Progress({timeline,status}){const current=stepFromStatus(status),rejected=isRejected(status);return <div style={{overflowX:"auto",padding:"6px 0"}}><div style={{display:"flex",alignItems:"center",minWidth:360,marginBottom:18}}>{STEPS.map((label,i)=>{const done=current>i+1||(current===4&&i===3),active=current===i+1,fail=rejected&&active;const bg=done?"#1E7F3E":fail?"#B01818":active?T.blue:T.border;return <div key={label} style={{display:"flex",alignItems:"center",flex:i<3?1:"none"}}><div style={{display:"grid",justifyItems:"center",gap:4,minWidth:62}}><div style={{width:31,height:31,borderRadius:"50%",display:"grid",placeItems:"center",background:bg,color:done||active||fail?"#fff":T.muted,fontWeight:800}}>{done?<CheckCircle2 size={16}/>:fail?<XCircle size={16}/>:i+1}</div><span style={{fontSize:10.5,color:T.muted,fontWeight:700}}>{label}</span></div>{i<3&&<div style={{flex:1,height:2,background:current>i+1?"#1E7F3E":T.border,marginBottom:18}}/>}</div>})}</div>{timeline?.length>0&&<div style={{borderLeft:`2px solid ${T.border}`,marginLeft:15,paddingLeft:18}}>{timeline.map((t,i)=><div key={`${t.tanggal}-${i}`} style={{marginBottom:13}}><div style={{fontSize:10.5,color:T.muted,lineHeight:1.45}}>{new Date(t.tanggal).toLocaleString("id-ID",{day:"2-digit",month:"long",year:"numeric",hour:"2-digit",minute:"2-digit"})} WIB · {t.oleh}</div><div style={{fontSize:12.5,fontWeight:700,color:T.heading,marginTop:2}}>{MITRA_STATUS_META[t.status]?.label||t.status}</div>{t.catatan&&<div style={{fontSize:12,color:T.muted,lineHeight:1.55,overflowWrap:"anywhere",marginTop:2}}>{t.catatan}</div>}</div>)}</div>}</div>}

function MitraForm({user,onSubmit,onClose}){
  const lockedOrg=!user?.isAdmin&&!!user?.organization;
  const [form,setForm]=useState({namaLembaga:user?.organization||"",kontakPIC:"",kontakTelp:"",judulPengajuan:"",nilaiDiajukan:"",deskripsi:""});
  const set=(k,v)=>setForm((p)=>({...p,[k]:v})); const input={width:"100%",padding:"10px 12px",borderRadius:8,border:`1px solid ${T.border}`,background:lockedOrg?T.bg:T.inputBg,color:T.text,boxSizing:"border-box",fontSize:13}; const label={display:"block",fontSize:11.5,fontWeight:700,color:T.heading,marginBottom:5};
  return <form onSubmit={(e)=>{e.preventDefault();if(!form.namaLembaga||!form.judulPengajuan)return;onSubmit({...form,nilaiDiajukan:Number(form.nilaiDiajukan)||0})}}><div style={{display:"grid",gap:13}}><div><label style={label}>Nama Perusahaan / Lembaga</label><input style={input} value={form.namaLembaga} onChange={(e)=>set("namaLembaga",e.target.value)} readOnly={lockedOrg} required/></div><div className="responsive-form-grid" style={{display:"grid",gridTemplateColumns:"repeat(2,minmax(0,1fr))",gap:12}}><div><label style={label}>Kontak PIC</label><input style={input} value={form.kontakPIC} onChange={(e)=>set("kontakPIC",e.target.value)}/></div><div><label style={label}>No. Telepon</label><input style={input} value={form.kontakTelp} onChange={(e)=>set("kontakTelp",e.target.value)}/></div></div><div><label style={label}>Judul Pengajuan</label><input style={input} value={form.judulPengajuan} onChange={(e)=>set("judulPengajuan",e.target.value)} required/></div><div><label style={label}>Nilai Diajukan (Rp)</label><input style={input} type="number" value={form.nilaiDiajukan} onChange={(e)=>set("nilaiDiajukan",e.target.value)}/></div><div><label style={label}>Deskripsi</label><textarea style={{...input,minHeight:88,resize:"vertical"}} value={form.deskripsi} onChange={(e)=>set("deskripsi",e.target.value)}/></div></div><div className="responsive-actions" style={{display:"flex",justifyContent:"flex-end",gap:10,marginTop:18}}><button type="button" onClick={onClose} style={secondary}>Batal</button><button type="submit" style={primary}><Send size={14}/>Kirim Pengajuan</button></div></form>
}

export default function PengajuanGandengPage({mitraList,setMitraList,user,notify,onBackToPortal}){
  const [showForm,setShowForm]=useState(false); const [detail,setDetail]=useState(null);
  const handleSubmit=(data)=>{const now=new Date().toISOString();const newItem={id:uid("MTR"),...data,ownerAccountId:user?.id||"",ownerEmail:user?.email||"",status:MITRA_STATUS.MENUNGGU_HUMAS,createdAt:now,timeline:[{status:MITRA_STATUS.MENUNGGU_HUMAS,tanggal:now,oleh:data.namaLembaga||"Pengaju",catatan:"Pengajuan diterima melalui GANDENG"}]};setMitraList((prev)=>[...prev,newItem]);setShowForm(false);notify?.("Pengajuan GANDENG berhasil dikirim.","success","Pengajuan GANDENG baru")};
  return <div style={{fontFamily:font.body,minWidth:0}}><PageHeader eyebrow="GANDENG" title="Pengajuan GANDENG" description={user?.isAdmin?"Daftar seluruh pengajuan GANDENG.":`Pengajuan milik ${user?.organization||user?.username||"akun ini"}. Akun lain tidak dapat melihat data pada halaman ini.`}/><div className="responsive-actions" style={{display:"flex",gap:10,marginBottom:18}}><button onClick={()=>setShowForm(true)} style={primary}><Plus size={15}/>Buat Pengajuan Baru</button>{onBackToPortal&&<button onClick={onBackToPortal} style={secondary}>Kembali ke Portal</button>}</div>{!mitraList.length?<Card><div style={empty}>Belum ada pengajuan GANDENG pada akun ini.</div></Card>:<Card padded={false}><div style={{overflowX:"auto"}}><table style={{width:"100%",minWidth:700,borderCollapse:"collapse",fontSize:12.5}}><thead><tr style={{background:T.bg}}>{["ID","Perusahaan / Lembaga","Judul Pengajuan","Nilai","Status",""].map((h)=><th key={h} style={th}>{h}</th>)}</tr></thead><tbody>{mitraList.map((m)=><tr key={m.id} onClick={()=>setDetail(m)} style={{cursor:"pointer"}}><td style={{...td,fontFamily:font.mono,fontWeight:800}}>{m.id}</td><td style={td}>{m.namaLembaga}</td><td style={{...td,maxWidth:250,overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap"}}>{m.judulPengajuan}</td><td style={{...td,whiteSpace:"nowrap"}}>{m.nilaiDiajukan?rupiah(m.nilaiDiajukan):"-"}</td><td style={td}><StatusBadge status={m.status}/></td><td style={td}><ChevronRight size={14}/></td></tr>)}</tbody></table></div></Card>}{showForm&&<Modal open onClose={()=>setShowForm(false)} title="Buat Pengajuan GANDENG Baru" icon={Plus} width={540}><MitraForm user={user} onSubmit={handleSubmit} onClose={()=>setShowForm(false)}/></Modal>}{detail&&<Modal open onClose={()=>setDetail(null)} title={`Detail Pengajuan - ${detail.id}`} icon={Eye} width={580}><div style={{display:"grid",gap:13}}><div className="responsive-form-grid" style={{display:"grid",gridTemplateColumns:"repeat(2,minmax(0,1fr))",gap:12}}><Info label="Perusahaan / Lembaga" value={detail.namaLembaga}/><Info label="Kontak PIC" value={detail.kontakPIC||"-"}/><Info label="Nilai Diajukan" value={detail.nilaiDiajukan?rupiah(detail.nilaiDiajukan):"-"}/><div><div style={infoLabel}>Status</div><StatusBadge status={detail.status}/></div></div><Info label="Judul Pengajuan" value={detail.judulPengajuan}/>{detail.deskripsi&&<Info label="Deskripsi" value={detail.deskripsi}/>}<div><div style={{fontSize:12.5,fontWeight:800,color:T.heading,marginBottom:10}}>Tracking Proses</div><Progress timeline={detail.timeline} status={detail.status}/></div></div></Modal>}</div>
}
function Info({label,value}){return <div style={{minWidth:0}}><div style={infoLabel}>{label}</div><div style={{fontSize:13,color:T.heading,fontWeight:650,lineHeight:1.5,overflowWrap:"anywhere"}}>{value}</div></div>}
const infoLabel={fontSize:10.5,color:T.muted,marginBottom:3}; const empty={padding:"32px 12px",textAlign:"center",color:T.muted,fontSize:13,lineHeight:1.6}; const th={padding:"11px 14px",textAlign:"left",fontWeight:800,color:T.heading,borderBottom:"1px solid var(--border)",fontSize:10.5,textTransform:"uppercase",letterSpacing:.3}; const td={padding:"12px 14px",borderBottom:"1px solid var(--border)",color:T.text}; const primary={display:"inline-flex",alignItems:"center",justifyContent:"center",gap:6,minHeight:40,padding:"0 16px",borderRadius:8,border:0,background:"var(--blue)",color:"#fff",cursor:"pointer",fontSize:12.5,fontWeight:800}; const secondary={display:"inline-flex",alignItems:"center",justifyContent:"center",gap:6,minHeight:40,padding:"0 16px",borderRadius:8,border:"1px solid var(--border)",background:"var(--card)",color:"var(--text)",cursor:"pointer",fontSize:12.5,fontWeight:700};
